"""
handlers/superadmin/admin_handler.py
─────────────────────────────────────────────────────────────
Super Admin dashboard entry point + emergency slash commands.

Emergency direct commands (bypass menus):
  /freeze_institution <org_id>
  /unfreeze_institution <org_id>
  /pause_registrations
  /resume_bot

Access: IsSuperAdmin filter (Telegram ID whitelist only).
─────────────────────────────────────────────────────────────
"""

from aiogram import Router, F
from aiogram.filters import Command
from aiogram.types import Message, CallbackQuery

from core.filters import IsSuperAdmin
from keyboards.superadmin_kb import superadmin_dashboard_keyboard
from keyboards.common_kb import nav_only_keyboard
from services.superadmin_service import (
    freeze_institution,
    pause_registrations,
    resume_registrations,
    enable_maintenance_mode,
    disable_maintenance_mode,
    get_platform_analytics,
)

router = Router()
router.message.filter(IsSuperAdmin())
router.callback_query.filter(IsSuperAdmin())


# ── Dashboard ─────────────────────────────────────────────

@router.callback_query(F.data == "sa:dashboard")
async def cb_sa_dashboard(callback: CallbackQuery) -> None:
    await callback.answer()
    await callback.message.edit_text(
        "🛡 <b>Naganaverse Control Center</b>\n\nRole: Super Admin",
        reply_markup=superadmin_dashboard_keyboard(),
    )


# ── Emergency Direct Commands ─────────────────────────────

@router.message(Command("freeze_institution"))
async def cmd_freeze_institution(message: Message) -> None:
    """
    /freeze_institution <org_id>
    Instantly freezes an institution without navigating menus.
    """
    parts = message.text.strip().split(maxsplit=1)
    if len(parts) < 2:
        await message.answer(
            "❌ Usage: /freeze_institution <org_id>\n"
            "<i>Example: /freeze_institution kinetic_classes</i>"
        )
        return

    org_id = parts[1].strip()
    result = await freeze_institution(org_id, message.from_user.id)
    await message.answer(result["message"], reply_markup=nav_only_keyboard())


@router.message(Command("pause_registrations"))
async def cmd_pause_reg(message: Message) -> None:
    text = await pause_registrations(message.from_user.id)
    await message.answer(text, reply_markup=nav_only_keyboard())

from aiogram.fsm.context import FSMContext
from aiogram.fsm.state import State, StatesGroup
from services.superadmin_service import push_to_notion
from config.config import settings

# ── States for Notion Sync ────────────────────────────────
class NotionSyncState(StatesGroup):
    waiting_for_passkey = State()
    waiting_for_payload = State()

# ── Notion Sync Commands ──────────────────────────────────

@router.message(Command("sync_notion"))
async def cmd_sync_notion(message: Message, state: FSMContext) -> None:
    """Starts the secure sync process."""
    await message.answer("🔐 <b>Naganaverse Auth</b>\nEnter Super-Admin Passkey to unlock Notion Sync:")
    await state.set_state(NotionSyncState.waiting_for_passkey)

@router.message(NotionSyncState.waiting_for_passkey)
async def process_notion_passkey(message: Message, state: FSMContext) -> None:
    """Validates the passkey."""
    if message.text == settings.NOTION_PASSKEY:
        await message.answer("✅ <b>Passkey Correct.</b>\nPaste the JSON payload generated by Gemini now:")
        await state.set_state(NotionSyncState.waiting_for_payload)
    else:
        await message.answer("❌ <b>Incorrect Passkey.</b> Sync cancelled.", reply_markup=nav_only_keyboard())
        await state.clear()

@router.message(NotionSyncState.waiting_for_payload)
async def process_notion_payload(message: Message, state: FSMContext) -> None:
    """Receives the JSON and pushes it."""
    # Call our new service
    result = await push_to_notion(message.text, message.from_user.id)
    
    await message.answer(result["message"], reply_markup=nav_only_keyboard())
    await state.clear()
  
@router.message(Command("resume_bot"))
async def cmd_resume_bot(message: Message) -> None:
    await resume_registrations(message.from_user.id)
    text = await disable_maintenance_mode(message.from_user.id)
    await message.answer(
        "✅ Bot fully resumed.\n" + text,
        reply_markup=nav_only_keyboard(),
    )
